### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test2 name",
  "email": "test2@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Users show
GET http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTI5NzE3Mjh9.-Uy1qBVNE8uhSfe7_lkswUtbe6IQe-mAx5fDdFxbUC4

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}